### ISSUE TITLE
6-1 체커 오작동

### ISSUE THREAD

**Issue by minty99** [kjp4155/pl-checker#18]
틀린 테스트 케이스가 있으면 즉시 종료해버리는 버그가 있습니다. check 파일의 set -e를 주석 처리하면 일단은 동작하긴 하는데, 확인 부탁드립니다.

**Comment by kjp4155** [comment]
@Jhuni0123  가 확인해줘영
저는 잘 몰라서..

**Comment by kjp4155** [comment]
말하는대로 하니까 되긴 되네요
근데 뭐 중요한게 아니라 따로 업데이트할 필요는 없을거같네요

**Comment by Jhuni0123** [comment]
의도한 동작은 아니라서 후에 고치도록 하겠습니다.
